### ISSUE TITLE
raspberry pi with 16.04 fails

### ISSUE THREAD

**Issue by hryamzik** [angstwad/docker.ubuntu#148]
```
TASK [docker : Install linux-image-extra-* packages to enable AuFS driver] *****
failed: [pi] (item=[u'linux-image-extra-4.4.0-1046-raspi2', u'linux-image-extra-virtual']) => {"failed": true, "item": ["linux-image-extra-4.4.0-1046-raspi2", "linux-image-extra-virtual"], "msg": "No package matching 'linux-image-extra-4.4.0-1046-raspi2' is available"}
```

May be related to #138.

**Comment by angstwad** [comment]
This is definitely the same issue as #138.  If you can come up with a cross-distro fix for the package names in that task, I'll take it.

**Comment by hryamzik** [comment]
Well, I'll try to figure out how to make it work on ARM. A bit confusing that it's a known issue but listed in closed ones...

**Comment by hryamzik** [comment]
@angstwad how about hardcoding some unsupported arcs? Here's what I currently use:

```yml
dependencies:
  - role: docker
    when: "{{ ansible_architecture != 'armv7l' }}"
```

```yml
- name: install docker.io
  apt: name=docker.io
  when: "{{ ansible_architecture == 'armv7l' }}"
```
