### ISSUE TITLE
need become: true for role to work

### ISSUE THREAD

**Issue by Bastien-** [angstwad/docker.ubuntu#159]
When I follow the [readme](https://github.com/angstwad/docker.ubuntu/blob/master/README.md) and do:

```
---
- name: Run docker.ubuntu
  hosts: docker
  roles:
    - angstwad.docker_ubuntu
```
The installation aborts at the task:
`TASK [angstwad.docker_ubuntu : Install linux-image-extra-* packages to enable AuFS driver]`

with the error message:
`Failed to lock apt for exclusive operation`

When doing:

```
---
- name: Run docker.ubuntu
  hosts: docker
  become: true
  roles:
    - angstwad.docker_ubuntu
```
Docker is installed correctly.

With ubuntu 14.04.
