### ISSUE TITLE
Allow ssh port override and disable sudo on local_action

### ISSUE THREAD

**Issue by smo921** [angstwad/docker.ubuntu#2]
It would be helpful to allow the ssh port to be overridden based on the inventory file settings.  I can submit a PR if you'd like but its really just changing the two lines in tasks/main.yml

```
- name: Wait for instance to come online
  local_action:
    module: wait_for
    host: "{{ hostvars[server_name]['ansible_ssh_host'] }}"
    port: "{{ hostvars[server_name]['ansible_ssh_port'] }}"
    delay: 30
    timeout: 600
    state: started
  sudo: no
  when: "ansible_distribution_version == '12.04' and reboot_result|success"
```

EDIT:  Additionally, explicitly disabling sudo for the local_action port check is nice.  It seems that local_action with sudo enabled is annoying and requires

1) /etc/sudoers to have NOPASSWD enabled for the user OR
2) possibly setting the sudoers password when running ansible

I didn't try the second approach honestly, as disabling sudo works just as well if not arguably better.
