### ISSUE TITLE
Need bip set before installing in some networking situations

### ISSUE THREAD

**Issue by thejmazz** [angstwad/docker.ubuntu#209]
Work wifi is `172.17.x.x/24` which conflicts with default docker bip of `172.17.0.1/16`, so if `daemon.json` is not set before installing, ansible loses ssh connection and fails. I've remedied this myself with the following playbook:

```yaml
---
- name: Install Docker on Ubuntu 16.04

  hosts: all
  become: true
  become_user: root

  vars:
    bip: 10.100.0.1/24
    storage_driver: overlay2
    pre_daemon_json:
      bip: "{{ bip }}"
      storage-driver: "{{ storage_driver }}"

  pre_tasks:
    - name: Ensure /etc/docker is present
      file:
        path: /etc/docker
        state: directory
        owner: root
        group: root
        mode: 0755
    - name: Set /etc/docker/daemon.json
      copy:
        content: "{{ pre_daemon_json | to_nice_json }}"
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: 0644

  roles:
    - role: angstwad.docker_ubuntu
      docker_pkg_name: "docker-ce={{ docker_version }}*"
      docker_aufs_enabled: false
      daemon_json: "{{ pre_daemon_json }}"
      pip_version_docker_compose: "{{ docker_compose_version }}"
      docker_group_members: [ 'ubuntu' ]
```
