### ISSUE TITLE
3.9.0 not released on ansible galaxy?

### ISSUE THREAD

**Issue by PikachuEXE** [angstwad/docker.ubuntu#239]
https://galaxy.ansible.com/angstwad/docker_ubuntu

![image](https://user-images.githubusercontent.com/1018543/89602391-36d8df80-d899-11ea-84af-3be57af1a762.png)

**Comment by PikachuEXE** [comment]
While it's not available yet on galaxy
I put this in my `requirements.yml`

```yaml
---
# How to use this file?
# https://docs.ansible.com/ansible/latest/reference_appendices/galaxy.html#installing-multiple-roles-from-a-file
#
# To update roles you can run `ansible-galaxy install -r ansible/roles/requirements.yml --force`
- name: angstwad.docker_ubuntu
  src: git+https://github.com/angstwad/docker.ubuntu.git
  version: v3.9.0
```
