### ISSUE TITLE
Missing config for specifying version for pip package `docker-py` version

### ISSUE THREAD

**Issue by PikachuEXE** [angstwad/docker.ubuntu#27]
I am using docker `1.3.3`, and `docker-py` `0.6.0`.
On a new machine, I found out this role installed `docker-py` `0.7.0`, which uses a newer API version, and return error on every docker module task.

My current "fix":
```yaml
---
- name: Remove Docker-py with wrong version
  pip:
    name: "docker-py"
    state: "absent"
- name: Install Docker-py with correct version
  pip:
    name: "docker-py"
    state: "present"
    version: 0.6.0
```
