### ISSUE TITLE
Error when installing container: Warning: docker.utils.create_host_config() is deprecated.

### ISSUE THREAD

**Issue by matiasmm** [angstwad/docker.ubuntu#74]
I'm experiencing this issue:

```
failed: [orchestra_vm] => {"failed": true, "parsed": false}
BECOME-SUCCESS-jvspektsacgiiafyvmwdbucorbumxbth
/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py:486: UserWarning: docker.utils.create_host_config() is deprecated. Please use Client.create_host_config() instead.
  'docker.utils.create_host_config() is deprecated. Please use '
Killed
OpenSSH_6.9p1, LibreSSL 2.1.7
debug1: Reading configuration data /Users/matias/.ssh/config
debug1: /Users/matias/.ssh/config line 12: Applying options for orchestra_vm
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to 127.0.0.1 closed.
```

When using this configuration:
```
- name: redis containers
  docker:
    name: myredis
    image: redis
    command: redis-server --appendonly yes
    state: started
    expose:
    - 6379
    volumes_from:
    - mydata
```

Also, after receiving that error, my ssh connection breaks.

Looks like a problem with the version of docker-py and docker-compose. As a temporary solution, I've noticed there are variables that can be passed to use a specific version: pip_version_docker_py, pip_version_docker_compose. I've tried passing version '1.5' for both items but didn' t help. Any suggestion?
