### ISSUE TITLE
Unable to remove filesystem

### ISSUE THREAD

**Issue by caarlos0** [angstwad/docker.ubuntu#94]
I'm using the role like this:

```yaml
- name: Start sandbox
  docker:
    name: blah
    image: caarlos0/blah
    pull: always
    state: reloaded
    ports:
      - 5000:5000
```

It works the first time, but if I try to run it again, I got:

```
Unable to remove filesystem for e086067abf98152eeae0157b212ff7514b571412a081c810431b31c4e645f67b: remove /var/lib/docker/containers/e086067abf98152eeae0157b212ff7514b571412a081c810431b31c4e645f67b/shm
```

Am I doing something wrong?

I already updated the kernel and everything else.

```console
$ uname -a
Linux automation.prod.contaazul.local 3.13.0-83-generic #127-Ubuntu SMP Fri Mar 11 00:25:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ docker -v
Docker version 1.11.0, build 4dc5990
```
